language: minimal
before_install:
- openssl aes-256-cbc -K $encrypted_a6d1af4d3600_key -iv $encrypted_a6d1af4d3600_iv
  -in .deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
addons:
  ssh_known_hosts:
  - cmr-dev.jembi.org
  - cmr-staging.jembi.org
deploy:
- provider: script
  script: ssh bahmni@cmr-dev.jembi.org 'cd ~/git/cameroon-bahmni-omods;git pull;/sbin/service openmrs restart;;'
  on:
    branch: dev
- provider: script
  script: ssh bahmni@cmr-staging.jembi.org 'cd ~/git/cameroon-bahmni-omods;git pull;/sbin/service openmrs restart;'
  on:
    branch: staging
